# Generated by Django 5.0.6 on 2024-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='approach',
            field=models.CharField(blank=True, choices=[('REDUCE', 'Reduce'), ('ACCEPT', 'Accept'), ('AVOID', 'Avoid'), ('SHARE', 'Share'), ('TRANSFER', 'Transfer')], max_length=50),
        ),
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('MONITORING', 'Monitoring'), ('MITIGATING', 'Mitigating'), ('CONTINGENCY', 'Contingency'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='NEW', max_length=50),
        ),
    ]
